name: Validate PR

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:

      # Validate PR Type
      - name: Validate PR type
        id: check_type
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
        shell: bash
        run: |

          echo "================================"
          echo "Checking PR type..."
          echo "================================"

          VALID_TYPES=(
            "bugfix:"
            "new feature:"
            "refactor:"
            "breaking:"
            "docs:"
          )

          if [[ -z "$PR_BODY" ]]; then
            echo ""
            echo "❌ ERROR: PR description is empty."
            echo "Please select a PR type."
            exit 1
          fi

          MATCH_COUNT=0
          MATCHED_TYPE=""

          for TYPE in "${VALID_TYPES[@]}"
          do

            if printf "%s\n" "$PR_BODY" \
              | grep -qiE "^[[:space:]]*-[[:space:]]*\[[xX]\][[:space:]]*$TYPE"
            then

              MATCH_COUNT=$((MATCH_COUNT+1))
              MATCHED_TYPE="$TYPE"

            fi

          done

          if [[ "$MATCH_COUNT" -eq 0 ]]
          then
            echo ""
            echo "❌ ERROR: No PR type selected."
            echo ""
            echo "Available types:"
            printf " - %s\n" "${VALID_TYPES[@]}"
            exit 1
          fi

          if [[ "$MATCH_COUNT" -gt 1 ]]
          then
            echo ""
            echo "❌ ERROR: Multiple PR types selected."
            echo ""
            echo "Only one type is allowed."
            exit 1
          fi

          echo ""
          echo "✅ PR type:"
          echo "$MATCHED_TYPE"
          echo ""
          echo "PR type validation passed."

      # Validate Branch
      - name: Validate branch name
        id: check_branch
        env:
          HEAD_BRANCH: ${{ github.event.pull_request.head.ref }}
        shell: bash
        run: |

          echo "================================"
          echo "Checking branch name..."
          echo "================================"

          echo "Branch:"
          echo "$HEAD_BRANCH"


          if [[ "$HEAD_BRANCH" == "main" ||
                "$HEAD_BRANCH" == "master" ]]
          then

            echo ""
            echo "❌ ERROR:"
            echo "Direct PR from main/master is forbidden."

            exit 1

          fi

          echo ""
          echo "✅ Branch validation passed."

      # Final Result
      - name: Validation result
        if: failure()
        shell: bash
        run: |

          echo ""
          echo "================================"
          echo "❌ PR validation failed"
          echo "================================"

          echo ""
          echo "Please fix the above errors."
          
          exit 1
